library(PasswordGen)

password()
password(no_words = 7, numbers = FALSE, symbols = FALSE, sep = ' ')
password(no_words = 3, numbers = FALSE, symbols = FALSE, sep = '_')
password(no_words = 3, numbers = FALSE, symbols = TRUE, sep = '_')
password(no_words = 4, numbers = TRUE, symbols = FALSE, sep = '-')
password(1)
password(2)
password()